first run
gingrm02/genisys pull request #9
Opened 2023-10-17 22:37 UTC by r-akers

2023-10-19 18:18 UTC, gingrm02 requested changes

2023-10-19 18:18 UTC, gingrm02 commented on genisys/main.py
> +    netplan = importlib.import_module("genisys/modules/netplan.py")
Lets covert these to import statements as discussed before merging this

2023-10-20 18:02 UTC, HenrithicusGreenson approved these changes

2023-10-20 18:25 UTC, patedm01 approved these changes

2023-10-21 00:52 UTC, BBergle approved these changes

2023-10-24 19:54 UTC, gingrm02 approved these changes
I'm approving this since we need it merged to address some of the comments. Lets talk through the system architecture soon to help understand some of my comments.

2023-10-24 19:54 UTC, gingrm02 commented on genisys/main.py
> +    netplan = net.Netplan()
Needs config passed to the constructor.

2023-10-24 19:54 UTC, gingrm02 commented on genisys/main.py
> +    netgenerate = net.generate()
Generate should not have to be called manually on modules. Lets talk about the class inheritance architecture on the modules at some point.

2023-10-24 19:54 UTC, gingrm02 commented on genisys/main.py
> +    import modules.base as base
Base should be treated as an abstract class. It is only meant to be inherited by the other modules, not instantiated directly.

2023-10-24 19:54 UTC, gingrm02 commented on genisys/main.py
> +    import genisys.configParser as cp
The run function shouldn't need to make it's own instance of the configParser. The main function will parse the config based on certain command line options then pass that instance of the config to the run function.

2023-10-24 20:37 UTC, closed without merging